project_id = "uulftjrvwmybplaeiyll"

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.manage-employee]
verify_jwt = false

[functions.register-user]
verify_jwt = false

[functions.seed-admin]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.process-order]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false
